// <auto-generated />
namespace Membership_App.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ProductLinkTexttableadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProductLinkTexttableadded));
        
        string IMigrationMetadata.Id
        {
            get { return "202008061517456_ProductLinkText table added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
