// <auto-generated />
namespace Membership_App.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ThreecustomcolumnswasaddedtoIdentityUsertable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ThreecustomcolumnswasaddedtoIdentityUsertable));
        
        string IMigrationMetadata.Id
        {
            get { return "202008061555580_Three custom columns was added to IdentityUser table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
